import { ScrollView, Text, Button } from 'react-native';
import { useRouter } from 'expo-router';
import { colors } from '../constants/theme';
export default function Privacy() {
  const router = useRouter();
  const sections = [
    ['Invited beta', 'Crossline operates this free invited beta and provides reference information for travel. Coverage is incomplete. Reviewed guidance is limited to the saved profile and stated conditions; it is not a legal determination. Verify official sources before acting. All beta features are free and purchases are disabled.'],
    ['Research notes and coverage', 'The reference library covers 14 Atlantic coastal states. Notes include official links, a research date and unresolved questions. Research notes are not independently reviewed legal guidance and never determine your carry-status color. A missing summary or an out-of-scope state does not mean there are no restrictions. Opening source links contacts the linked website.'],
    ['Google sign-in', 'If you choose Continue with Google, Google authenticates you and shares basic identity information, including your account identifier, email and profile information, with Supabase Auth. Crossline does not request access to Gmail messages, Drive files or contacts. Deleting your Crossline account does not delete your Google account.'],
    ['Your account', 'Supabase stores your email and authentication information, home state, permits and firearm profile. Access rules restrict personal records to your account; authorized service administrators can access data to operate and support the service. Account deletion removes your profile, permits and saved crossing history from the active database; provider backups may persist under the provider’s retention schedule.'],
    ['Location and history', 'With your permission, the device checks coordinates against state boundaries. Crossline does not upload a continuous GPS track. The last state and a candidate crossing are stored on this device to prevent duplicate alerts. Optional saved history contains state codes and crossing times in your account, not exact coordinates. History saving starts off. You can stop tracking, turn off alerts, clear history or delete your account in Profile.'],
    ['Trip planning', 'Manual state planning does not contact a directions provider. When configured, address searches go to OpenCage and driving-route coordinates go to the configured routing provider. Saved trip briefs stay on this device and include their download date. Clear them in Trip or sign out to remove them.'],
    ['Map and network services', 'The browser street map loads tiles from OpenStreetMap, whose servers receive your IP address and the map areas you view. Browser location updates while the map is open; precise coordinates are not uploaded to Crossline. The native map uses Apple Maps on iOS and Google Maps on Android. Loading map content makes requests to the platform’s map provider. Supabase and other contacted services may process network metadata such as IP addresses and request logs. Their retention settings and policies also apply.'],
    ['Device storage', 'Session tokens, preferences and saved briefs use app-local storage. This storage is not an encrypted document vault. Device backups may include app data depending on your operating-system settings. Signing out clears saved Crossline briefs and preferences on this device; it does not erase backups or copies on other devices.'],
    ['Permissions and reliability', 'You can use the law browser without granting location permission. Background alerts require an installed mobile build, location permission and notification permission. Operating-system restrictions, low battery and force-quitting can interrupt tracking. Missing or stale rules produce an undetermined status.'],
    ['Questions and feedback', 'During the invited beta, contact the person who invited you for support or to report incorrect information. Do not include passwords, permit documents or precise location history in public issue reports.'],
  ];
  return <ScrollView style={{ backgroundColor: colors.navy }} contentContainerStyle={{ padding: 28, paddingTop: 65, gap: 18 }}><Text style={{ color: colors.white, fontSize: 28 }}>Privacy & beta information</Text>{sections.map(([title,body]) => <Text key={title} style={{ color: colors.silver, fontSize: 16, lineHeight: 24 }}><Text style={{ color: colors.white, fontWeight: 'bold' }}>{title}{'\n'}</Text>{body}</Text>)}<Button title="Back" onPress={() => router.canGoBack() ? router.back() : router.replace('/')} /></ScrollView>;
}
